# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BIIfW6IL4LdAkaoiUM6QbkTlwEZFU0l-
"""

# ==============================================
# QUOTATION SYSTEM - AIA MediFlex-i (PLAN 250)
# VERSI BETUL: Class 1,2,3 = rate sama
# ==============================================

# Data kadar (RM500 Deductible, Plan 250)
base_annual_male = {
    20:1220,21:1269,22:1289,23:1298,24:1300,25:1306,26:1369,27:1371,28:1373,29:1386,
    30:1405,31:1469,32:1492,33:1511,34:1545,35:1566,36:1584,37:1618,38:1639,39:1656,
    40:1673,41:1800,42:1875,43:1938,44:2027,45:2049,46:2176,47:2252,48:2396,49:2458,
    50:2554,51:2960,52:3230,53:3380,54:3470,55:3620
}

base_annual_female = {
    20:1237,21:1259,22:1283,23:1294,24:1305,25:1317,26:1329,27:1340,28:1351,29:1363,
    30:1374,31:1511,32:1534,33:1580,34:1603,35:1626,36:1637,37:1694,38:1740,39:1786,
    40:1809,41:1924,42:1957,43:1992,44:2038,45:2266,46:2381,47:2496,48:2610,49:2725,
    50:2827,51:2949,52:3070,53:3200,54:3340,55:3740
}

# Data booster
booster_male = {
    20:206,21:224,22:224,23:224,24:224,25:224,26:224,27:224,28:224,29:224,
    30:252,31:252,32:252,33:252,34:252,35:252,36:273,37:273,38:273,39:273,
    40:301,41:301,42:301,43:301,44:301,45:301,46:331,47:331,48:331,49:331,50:368
}

booster_female = {
    20:196,21:208,22:208,23:208,24:208,25:208,26:208,27:208,28:208,29:208,
    30:231,31:231,32:231,33:231,34:231,35:231,36:250,37:250,38:250,39:250,
    40:250,41:279,42:279,43:279,44:279,45:279,46:294,47:294,48:294,49:294,50:311
}

def quotation(age, gender, with_booster, job_class):
    if gender == 'Male':
        base = base_annual_male.get(age)
        booster = booster_male.get(age, 0)
    else:
        base = base_annual_female.get(age)
        booster = booster_female.get(age, 0)

    if base is None:
        return None

    total = base + (booster if with_booster else 0)

    # ⚠️ HANYA Class 4 yang ada loading (anda akan isi nanti)
    # Class 1,2,3 = rate sama (0% loading)
    if job_class == 4:
        # Untuk Class 4, loading 40% (anda boleh ubah nanti)
        total = total * 1.40
    # Class 1,2,3 TIADA loading

    return {
        'age': age,
        'gender': gender,
        'coverage': 'RM1,000,000' if with_booster else 'RM250,000',
        'job_class': job_class,
        'monthly': round(total / 12, 2),
        'annual': round(total, 2),
        'loading': '0%' if job_class != 4 else '40%'
    }

print("="*50)
print("   QUOTATION SYSTEM - AIA MediFlex-i")
print("   Class 1,2,3 = rate sama")
print("="*50)

# Senarai contoh quotation
quotes = [
    {'age': 35, 'gender': 'Male', 'booster': True, 'job': 1},
    {'age': 35, 'gender': 'Male', 'booster': True, 'job': 2},
    {'age': 35, 'gender': 'Male', 'booster': True, 'job': 3},
    {'age': 40, 'gender': 'Female', 'booster': False, 'job': 1},
    {'age': 30, 'gender': 'Male', 'booster': True, 'job': 3},
    {'age': 45, 'gender': 'Female', 'booster': True, 'job': 1},
    {'age': 50, 'gender': 'Male', 'booster': False, 'job': 2},
]

for q in quotes:
    result = quotation(q['age'], q['gender'], q['booster'], q['job'])
    if result:
        print(f"\n✅ Umur: {result['age']} | {result['gender']} | Job Class {result['job_class']} (Loading: {result['loading']})")
        print(f"   Coverage: {result['coverage']}")
        print(f"   💰 Bulanan: RM{result['monthly']} | Tahunan: RM{result['annual']}")
    else:
        print(f"\n❌ Data untuk umur {q['age']} tidak tersedia")

print("\n" + "="*50)
print("Nota: Class 4 belum diisi data. Anda akan isi manual nanti.")
print("Untuk quotation lain, ubah nilai dalam senarai 'quotes'")
print("="*50)

quotation(37, 'Male', True, 1)